import { type FC } from "react";
import { useExperienceTimeline } from "./use-experience-timeline";

export const Experience: FC = () => {
  useExperienceTimeline();

  return (
    <div id="experience" className="experience w-screen">
      <div className="experience-header top-0 left-0 w-full h-12 flex items-center px-6 py-4 space-x-2">
        <div className="w-3 h-3 bg-white"></div>
        <h2 className="text-lg uppercase mono text-gray-400">EXPERIENCE</h2>
      </div>

      <section className="experience-body max-w-6xl h-full mx-auto px-6 py-12">
        <h3 className="experience-title mono text-4xl lg:text-5xl leading-tight uppercase py-6 font-light text-gray-200 mb-16">
          WORK HISTORY
        </h3>

        <div className="timeline-container relative">
          <div className="relative flex items-start">
            <div className="w-full">
              <div className="bg-white/5 rounded-2xl p-8 border border-white/10 hover:bg-white/10 transition-all duration-300">
                <div>
                  <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between mb-6">
                    <img src="/worlds-logo.png" alt="Worlds" className="w-64" />
                    <span className="text-sm text-gray-400 mono bg-white/10 px-3 py-1 rounded-full">
                      Feb. 2019 - Today
                    </span>
                  </div>

                  <div>
                    <h4 className="text-xl mono uppercase font-light">
                      UI Team Lead
                    </h4>

                    <ul className="space-y-4 mb-6 list-disc list-inside">
                      <li className="text-gray-300 leading-relaxed">
                        Led the development of an AI chat interface written in
                        TypeScript and React, which communicates with an LLM
                        (Gemma) to find and describe objects that have been
                        previously detected by Worlds' computer vision models.
                      </li>
                      <li className="text-gray-300 leading-relaxed">
                        Led the development of AIMS, a monitoring interface for
                        the US Air Force using React and TypeScript, ensuring
                        real-time security compliance on military bases.
                      </li>
                      <li className="text-gray-300 leading-relaxed">
                        Developed Worlds NQ using React and TypeScript, enabling
                        data scientists to efficiently tag training data for
                        object detection models. Decreased model deployment time
                        by about 75%.
                      </li>
                      <li className="text-gray-300 leading-relaxed">
                        Led a team of two engineers, translating product goals
                        into requirements, features, and tasks. Prioritized and
                        assigned work while mentoring team members and
                        conducting code reviews to ensure delivery.
                      </li>
                    </ul>
                  </div>

                  <div>
                    <h4 className="text-xl font-light mono uppercase">
                      Software Engineer
                    </h4>

                    <ul className="space-y-4 mb-6 list-disc list-inside">
                      <li className="text-gray-300 leading-relaxed">
                        Led the design and development of the Worlds API and its
                        documentation: A GraphQL API written in Java Spring Boot
                        that exposes data generated by the Worlds platform to
                        the public. Enables forward-deployed and client
                        engineering teams to self-serve integrations, reducing
                        the internal engineering team's bespoke solution
                        workload by about 90%.
                      </li>
                      <li className="text-gray-300 leading-relaxed">
                        Designed and developed Worlds Navigator in TypeScript,
                        React, and Babylon.js, which simulates clients' site
                        activity and events in real-time within their digital
                        twins.
                      </li>
                      <li className="text-gray-300 leading-relaxed">
                        Proposed, designed, and developed Worlds Builder using
                        TypeScript, React and Babylon.js on the front-end and
                        Java and Spring Boot on the back-end. Allows internal
                        support teams and clients to create and maintain digital
                        twins. Resulted in a 50% decrease in client onboarding
                        time.
                      </li>
                      <li className="text-gray-300 leading-relaxed">
                        Developed Worlds Calibration, a Python microservice that
                        enables the real-time simulation of clients' digital
                        twins by attaching global positioning data to objects
                        detected by computer vision models. The underlying logic
                        has been incorporated into multiple awarded patents.
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};
